name: build
on:
  push:
  workflow_dispatch:
  
env:
  CW_LLVM_MINGW_DL: '1'
  CW_LLVM_MINGW_ONLY: '0'
  CW_CONFIG: main-win-gcc-pico-small

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main
        with:
          repository: curl/curl-for-win
          fetch-depth: '10'
      - name: 'build'
        run: |
          . ./_versions.sh
          docker trust inspect --pretty "${DOCKER_IMAGE}"
          time docker pull "${DOCKER_IMAGE}"
          docker images --digests
          time docker run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_|DO_NOT_TRACK)') \
            "${DOCKER_IMAGE}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: |
          rm *.xz *.xz.txt
          cat urls.txt *-version-*.txt || true
      - uses: actions/upload-artifact@main
        with:
          name: 'curl-win-gcc-pico'
          path: |
            *-*-mingw*.*
            urls.txt
